author: "Julie Orjuela & Sebastien Cunnac"
format:
  html:
    toc: true
    code-fold: false
    toc-title: Section Contents
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
  
project:
  type: default
  execute-dir: project
  output-dir: "/home/cunnac/Lab-Related/MyScripts/cibig-wave.github.io/docs/course_materials/R/.local"
