# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            CIBiG
tagline:          'One month course'
description:      'From sequencing data production to analysis for agriculture and health'
#baseurl: ""
url:              'cibig-wave.github.io'
author:
  name:           'Christine Tranchant-Dubreuil'
  mail:            christine.tranchant@ird.fr'


#paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/CIBiG-wave/cibig-wave.github.io

exclude:
  -course_materials/ALGO/readme.md
  -course_materials/BANK/readme.md
  -course_materials/DATA_ANALYSIS/readme.md
  -course_materials/GIT/readme.md
  -course_materials/LINUX1/README.md
  -course_materials/LINUX1/linux1_PRACTICE.md
  -course_materials/LINUX2/README.md
  -course_materials/LINUX2/linux2_PRACTICE.md
  -course_materials/R/README.md
  -course_materials/REPRO/readme.md
  -course_materials/REPRO/CONTAINERS/readme.md
  -course_materials/REPRO/CONTAINERS/CONTAINERS_practice.md
  -course_materials/SLURM/readme.md
  -course_materials/SLURM/slurm.md
  -README.md
