# -------------------------------------------------------------
#  CIBiG  International Certificate in Bioinformatics and Genomics
#  Global configuration file for the GitHubPages site (Jekyll)
# -------------------------------------------------------------

# --- Site settings -----------------------------------------------------------

title: "CIBiG"
tagline: "One month intensive course"
description: "Training in sequencing technologies, genomics and bioinformatics with a focus on agriculture and health applications."
lang: fr
url: "https://wave-centre.github.io/cibig/"      # full base URL
baseurl: ""                               # repository root (for orgsite)
github:
  repo:           https://github.com/wave-centre/

# Author (used by JekyllSEOtag)
author:
  name: "Christine TranchantDubreuil"
  email: "christine.tranchant@ird.fr"

# --- Appearance & theme ------------------------------------------------------

# Preferred remote theme (comment out if you stick to the default GitHub theme)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# If you prefer GitHub default theme, comment the line above and uncomment:
# theme: jekyll-theme-minimal

# --- Plugins -----------------------------------------------------------------
plugins:
  - jekyll-feed          # RSS feed
  - jekyll-seo-tag       # SEO metatags
  - jekyll-sitemap       # sitemap.xml
  - jekyll-remote-theme  # required for remote_theme

# --- Defaults (applied to every markdown page) -------------------------------

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

# --- Navigation (for MinimalMistakes) ---------------------------------------
# Create a menu via _data/navigation.yml (see documentation) -------------------

# --- Collections (optional) ---------------------------------------------------
collections:
   sessions:
     output: true
     permalink: /sessions/2025/

# --- Build settings -----------------------------------------------------------

# Exclude files/folders from the build
exclude:
  - course_materials/*
  - README.md
  - Gemfile*

# Keep files/folders that are normally excluded
# keep_files:
#   - "assets/img"

# Enable incremental build locally
# incremental: true

# Timezone (optional)
# timezone: "Africa/Abidjan"

